import { useState, useEffect, useRef } from 'react'
import { Link } from 'react-router-dom'
import {
  collection,
  query,
  orderBy,
  onSnapshot,
  limit,
  getDocs,
  doc,
  updateDoc,
  serverTimestamp
} from 'firebase/firestore'
import { db } from '../../lib/firebase'
import { useAuth } from '../../contexts/AuthContext'
import { Project, Workstream, ActionTag, WorkType } from '../../types'
import { Spinner } from '../../components/Spinner'

interface WorkstreamWithSummary extends Workstream {
  summary?: string
  actionTag?: ActionTag
  workType?: WorkType
  updateCount: number
  summaryGeneratedAt?: any // Firestore Timestamp
}

interface ProjectWithWorkstreams extends Project {
  workstreams: WorkstreamWithSummary[]
}

export function ProjectsPage() {
  const { user } = useAuth()
  const [projects, setProjects] = useState<ProjectWithWorkstreams[]>([])
  const [loading, setLoading] = useState(true)
  const [generatingSummary, setGeneratingSummary] = useState<string | null>(null)
  const autoGeneratedRef = useRef(false)

  useEffect(() => {
    if (!user) return

    const projectsRef = collection(db, 'users', user.uid, 'projects')
    const q = query(projectsRef, orderBy('lastActivityAt', 'desc'))

    const unsubscribe = onSnapshot(q, async (snapshot) => {
      const projectList: ProjectWithWorkstreams[] = []

      for (const docSnap of snapshot.docs) {
        const projectData = { id: docSnap.id, ...docSnap.data() } as Project

        // Get workstreams with their summaries
        const workstreamsRef = collection(docSnap.ref, 'workstreams')
        const workstreamsQuery = query(workstreamsRef, orderBy('lastActivityAt', 'desc'), limit(3))
        const workstreamsSnap = await getDocs(workstreamsQuery)

        const workstreams: WorkstreamWithSummary[] = []
        for (const wsDoc of workstreamsSnap.docs) {
          const wsData = wsDoc.data()

          // Get update count for this workstream
          const updatesRef = collection(wsDoc.ref, 'updates')
          const updatesSnap = await getDocs(query(updatesRef, limit(20)))

          workstreams.push({
            id: wsDoc.id,
            ...wsData,
            summary: wsData.aiSummary || undefined,
            actionTag: wsData.actionTag || undefined,
            workType: wsData.workType || undefined,
            updateCount: updatesSnap.size,
            summaryGeneratedAt: wsData.summaryGeneratedAt || undefined
          } as WorkstreamWithSummary)
        }

        projectList.push({
          ...projectData,
          workstreams
        })
      }

      setProjects(projectList)
      setLoading(false)
    })

    return () => unsubscribe()
  }, [user])

  // Reset auto-generate guard when user changes
  useEffect(() => {
    autoGeneratedRef.current = false
  }, [user?.uid])

  // Auto-generate summaries for stale workstreams on page load
  useEffect(() => {
    if (loading || autoGeneratedRef.current || projects.length === 0) return

    const checkStaleSummary = (ws: WorkstreamWithSummary): boolean => {
      // No summary yet - needs generation
      if (!ws.summary) return true

      // Has summary but no timestamp - consider stale
      if (!ws.summaryGeneratedAt) return true

      // Compare summaryGeneratedAt with lastActivityAt
      const summaryTime = ws.summaryGeneratedAt?.toDate?.()?.getTime() || 0
      const activityTime = ws.lastActivityAt?.toDate?.()?.getTime() || 0

      // Summary is stale if activity happened after it was generated
      return activityTime > summaryTime
    }

    const autoGenerateStaleSummaries = async () => {
      autoGeneratedRef.current = true

      // Get first 3 projects, find stale workstreams
      const staleWorkstreams: { projectId: string; workstreamId: string }[] = []

      for (const project of projects.slice(0, 3)) {
        for (const ws of project.workstreams) {
          if (checkStaleSummary(ws) && staleWorkstreams.length < 5) {
            staleWorkstreams.push({ projectId: project.id, workstreamId: ws.id })
          }
        }
      }

      // Generate summaries sequentially to avoid rate limits
      for (const { projectId, workstreamId } of staleWorkstreams) {
        await generateSummaryForWorkstream(projectId, workstreamId)
      }
    }

    autoGenerateStaleSummaries()
  }, [loading, projects.length])

  // Extracted summary generation logic for reuse
  const generateSummaryForWorkstream = async (projectId: string, workstreamId: string) => {
    if (!user) return

    try {
      const tokensRef = collection(db, 'users', user.uid, 'agentTokens')
      const tokensSnap = await getDocs(query(tokensRef))
      const activeToken = tokensSnap.docs.find(doc => !doc.data().isRevoked)

      if (!activeToken) return

      const token = activeToken.data().token

      const response = await fetch('https://us-central1-town-center-agent.cloudfunctions.net/summarize', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Agent-Token': token
        },
        body: JSON.stringify({ projectId, workstreamId })
      })

      const data = await response.json()

      if (response.ok && data.success && data.summary) {
        const wsRef = doc(db, 'users', user.uid, 'projects', projectId, 'workstreams', workstreamId)
        await updateDoc(wsRef, {
          aiSummary: data.summary,
          actionTag: data.actionTag || null,
          workType: data.workType || null,
          summaryGeneratedAt: serverTimestamp()
        })

        setProjects(prev => prev.map(project => {
          if (project.id !== projectId) return project
          return {
            ...project,
            workstreams: project.workstreams.map(ws => {
              if (ws.id !== workstreamId) return ws
              return {
                ...ws,
                summary: data.summary,
                actionTag: data.actionTag || undefined,
                workType: data.workType || undefined,
                summaryGeneratedAt: new Date()
              }
            })
          }
        }))
      }
    } catch (error) {
      console.error('Error auto-generating summary:', error)
    }
  }

  const generateSummary = async (projectId: string, workstreamId: string) => {
    if (!user) return

    setGeneratingSummary(`${projectId}-${workstreamId}`)

    try {
      // Get user's active (non-revoked) token
      const tokensRef = collection(db, 'users', user.uid, 'agentTokens')
      const tokensSnap = await getDocs(query(tokensRef))

      // Find first non-revoked token
      const activeToken = tokensSnap.docs.find(doc => !doc.data().isRevoked)

      if (!activeToken) {
        alert('No active tokens found. Please create a new agent token in the Tokens page.')
        return
      }

      const tokenData = activeToken.data()
      const token = tokenData.token

      // Call summarize endpoint
      const response = await fetch('https://us-central1-town-center-agent.cloudfunctions.net/summarize', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Agent-Token': token
        },
        body: JSON.stringify({ projectId, workstreamId })
      })

      const data = await response.json()

      if (!response.ok) {
        alert(`Error: ${data.error || 'Unknown error'}`)
        return
      }

      if (data.success && data.summary) {
        // Cache the summary, action tag, and work type in the workstream document
        const wsRef = doc(db, 'users', user.uid, 'projects', projectId, 'workstreams', workstreamId)
        await updateDoc(wsRef, {
          aiSummary: data.summary,
          actionTag: data.actionTag || null,
          workType: data.workType || null,
          summaryGeneratedAt: serverTimestamp()
        })

        // Update local state immediately (onSnapshot doesn't trigger for workstream changes)
        setProjects(prev => prev.map(project => {
          if (project.id !== projectId) return project
          return {
            ...project,
            workstreams: project.workstreams.map(ws => {
              if (ws.id !== workstreamId) return ws
              return {
                ...ws,
                summary: data.summary,
                actionTag: data.actionTag || undefined,
                workType: data.workType || undefined,
                summaryGeneratedAt: new Date()
              }
            })
          }
        }))
      }
    } catch (error) {
      console.error('Error generating summary:', error)
    } finally {
      setGeneratingSummary(null)
    }
  }

  const formatRelativeTime = (timestamp: any) => {
    if (!timestamp) return ''
    const date = timestamp.toDate ? timestamp.toDate() : new Date(timestamp)
    const now = new Date()
    const diffMs = now.getTime() - date.getTime()
    const diffMins = Math.floor(diffMs / 60000)
    const diffHours = Math.floor(diffMs / 3600000)
    const diffDays = Math.floor(diffMs / 86400000)

    if (diffMins < 1) return 'just now'
    if (diffMins < 60) return `${diffMins}m ago`
    if (diffHours < 24) return `${diffHours}h ago`
    if (diffDays < 7) return `${diffDays}d ago`
    return date.toLocaleDateString()
  }

  const getStatusColor = (status: string) => {
    const colors = {
      active: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
      paused: 'bg-slate-100 text-slate-600 dark:bg-slate-700/50 dark:text-slate-400',
      completed: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400'
    }
    return colors[status as keyof typeof colors] || colors.active
  }

  const getActionTagStyle = (tag: ActionTag) => {
    const styles: Record<string, { color: string; label: string; icon: string }> = {
      needs_attention: {
        color: 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400',
        label: 'Needs attention',
        icon: '!'
      },
      question_pending: {
        color: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400',
        label: 'Question pending',
        icon: '?'
      },
      review_requested: {
        color: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400',
        label: 'Review requested',
        icon: '👁'
      },
      decision_needed: {
        color: 'bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-400',
        label: 'Decision needed',
        icon: '⚖'
      },
      ready_to_merge: {
        color: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
        label: 'Ready to merge',
        icon: '✓'
      },
      blocked: {
        color: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
        label: 'Blocked',
        icon: '⏸'
      },
      in_progress: {
        color: 'bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-400',
        label: 'In progress',
        icon: '→'
      }
    }
    return tag ? styles[tag] : null
  }

  if (loading) {
    return (
      <div className="flex justify-center py-12">
        <Spinner size="lg" />
      </div>
    )
  }

  if (projects.length === 0) {
    return (
      <div className="text-center py-12">
        <svg className="w-16 h-16 mx-auto text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
        </svg>
        <h2 className="mt-4 text-xl font-medium text-gray-900 dark:text-white">
          No projects yet
        </h2>
        <p className="mt-2 text-gray-600 dark:text-gray-400 max-w-md mx-auto">
          Projects will appear here automatically when your AI agents start posting updates.
        </p>
        <Link
          to="/tokens"
          className="inline-block mt-6 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
        >
          Create an Agent Token
        </Link>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
          Projects
        </h1>
        <p className="mt-1 text-gray-600 dark:text-gray-400">
          Activity from your AI development agents
        </p>
      </div>

      <div className="space-y-6">
        {projects.map((project) => (
          <div
            key={project.id}
            className="bg-white dark:bg-gray-800 rounded-lg shadow overflow-hidden"
          >
            {/* Project Header */}
            <Link
              to={`/projects/${project.id}`}
              className="block p-4 hover:bg-gray-50 dark:hover:bg-gray-700/50 transition-colors border-b border-gray-100 dark:border-gray-700"
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-lg bg-blue-100 dark:bg-blue-900/30 flex items-center justify-center">
                    <svg className="w-5 h-5 text-blue-600 dark:text-blue-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
                    </svg>
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-900 dark:text-white">
                      {project.name}
                    </h3>
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      {project.workstreams.length} branch{project.workstreams.length !== 1 ? 'es' : ''} · {formatRelativeTime(project.lastActivityAt)}
                    </p>
                  </div>
                </div>
                <svg className="w-5 h-5 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                </svg>
              </div>
            </Link>

            {/* Workstreams (Branches) */}
            {project.workstreams.length > 0 && (
              <div className="divide-y divide-gray-100 dark:divide-gray-700">
                {project.workstreams.map((ws) => (
                  <div
                    key={ws.id}
                    className="px-4 py-4"
                  >
                    <div className="flex items-start justify-between gap-3">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 mb-1 flex-wrap">
                          <svg className="w-4 h-4 text-gray-400 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                          </svg>
                          <Link
                            to={`/projects/${project.id}/workstreams/${ws.id}`}
                            className="font-medium text-gray-900 dark:text-white hover:text-blue-600 dark:hover:text-blue-400"
                          >
                            {ws.name}
                          </Link>
                          <span className={`text-xs px-2 py-0.5 rounded-full ${getStatusColor(ws.status)}`}>
                            {ws.status}
                          </span>
                          {ws.workType && (
                            <span className="text-xs px-2 py-0.5 rounded-full bg-gray-100 text-gray-500 dark:bg-gray-700 dark:text-gray-400">
                              {ws.workType}
                            </span>
                          )}
                          {ws.actionTag && getActionTagStyle(ws.actionTag) && (
                            <span
                              className={`text-xs px-2 py-0.5 rounded-full font-medium ${getActionTagStyle(ws.actionTag)!.color}`}
                              title={getActionTagStyle(ws.actionTag)!.label}
                            >
                              {getActionTagStyle(ws.actionTag)!.icon} {getActionTagStyle(ws.actionTag)!.label}
                            </span>
                          )}
                        </div>

                        {/* AI Summary or placeholder */}
                        {ws.summary ? (
                          <p className="text-sm text-gray-600 dark:text-gray-400 ml-6 mt-1 leading-relaxed">
                            {ws.summary}
                            <span className="text-gray-400 dark:text-gray-500"> · {formatRelativeTime(ws.lastActivityAt)}</span>
                          </p>
                        ) : (
                          <p className="text-sm text-gray-500 dark:text-gray-500 ml-6 mt-1 italic">
                            {ws.updateCount} commit{ws.updateCount !== 1 ? 's' : ''} · {formatRelativeTime(ws.lastActivityAt)}
                          </p>
                        )}
                      </div>

                      {/* Generate Summary Button */}
                      <button
                        onClick={(e) => {
                          e.preventDefault()
                          generateSummary(project.id, ws.id)
                        }}
                        disabled={generatingSummary === `${project.id}-${ws.id}`}
                        className="flex-shrink-0 p-1.5 text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded transition-colors disabled:opacity-50"
                        title={ws.summary ? "Refresh summary" : "Generate AI summary"}
                      >
                        {generatingSummary === `${project.id}-${ws.id}` ? (
                          <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                          </svg>
                        ) : (
                          <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                          </svg>
                        )}
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  )
}
