import { useState, useEffect, useRef } from 'react'
import { useParams, Link } from 'react-router-dom'
import {
  collection,
  doc,
  query,
  orderBy,
  limit,
  onSnapshot,
  getDocs,
  updateDoc,
  serverTimestamp
} from 'firebase/firestore'
import { db } from '../../lib/firebase'
import { formatRelativeTime } from '../../lib/utils'
import { useAuth } from '../../contexts/AuthContext'
import { Project, Workstream, Update } from '../../types'
import { Spinner } from '../../components/Spinner'

export function ProjectDetailPage() {
  const { projectId } = useParams<{ projectId: string }>()
  const { user } = useAuth()
  const [project, setProject] = useState<Project | null>(null)
  const [workstreams, setWorkstreams] = useState<Workstream[]>([])
  const [recentUpdates, setRecentUpdates] = useState<(Update & { workstreamName: string })[]>([])
  const [loading, setLoading] = useState(true)
  const [generatingProjectSummary, setGeneratingProjectSummary] = useState(false)
  const autoGeneratedRef = useRef(false)

  useEffect(() => {
    if (!user || !projectId) return

    // Listen to project
    const projectRef = doc(db, 'users', user.uid, 'projects', projectId)
    const unsubProject = onSnapshot(projectRef, (doc) => {
      if (doc.exists()) {
        setProject({ id: doc.id, ...doc.data() } as Project)
      }
    })

    // Listen to workstreams
    const workstreamsRef = collection(db, 'users', user.uid, 'projects', projectId, 'workstreams')
    const q = query(workstreamsRef, orderBy('lastActivityAt', 'desc'))
    const unsubWorkstreams = onSnapshot(q, async (snapshot) => {
      const list: Workstream[] = snapshot.docs.map(doc => ({
        id: doc.id,
        ...doc.data()
      } as Workstream))
      setWorkstreams(list)

      // Fetch recent updates from all workstreams
      const updates: (Update & { workstreamName: string })[] = []
      for (const wsDoc of snapshot.docs) {
        const wsData = wsDoc.data()
        const updatesRef = collection(wsDoc.ref, 'updates')
        const updatesQuery = query(updatesRef, orderBy('timestamp', 'desc'), limit(5))
        const updatesSnap = await getDocs(updatesQuery)
        updatesSnap.docs.forEach(uDoc => {
          updates.push({
            id: uDoc.id,
            ...uDoc.data(),
            workstreamName: wsData.name
          } as Update & { workstreamName: string })
        })
      }

      // Sort and take most recent
      updates.sort((a, b) => {
        const aTime = a.timestamp?.toDate?.() || new Date(0)
        const bTime = b.timestamp?.toDate?.() || new Date(0)
        return bTime.getTime() - aTime.getTime()
      })
      setRecentUpdates(updates.slice(0, 10))
      setLoading(false)
    })

    return () => {
      unsubProject()
      unsubWorkstreams()
    }
  }, [user, projectId])

  // Reset auto-generate guard when projectId changes
  useEffect(() => {
    autoGeneratedRef.current = false
  }, [projectId])

  // Auto-generate project summary if stale
  useEffect(() => {
    if (loading || !project || autoGeneratedRef.current) return

    const isStale = () => {
      if (!project.aiSummary) return true
      if (!project.summaryGeneratedAt) return true
      const summaryTime = (project.summaryGeneratedAt as any)?.toDate?.()?.getTime() || 0
      const activityTime = (project.lastActivityAt as any)?.toDate?.()?.getTime() || 0
      return activityTime > summaryTime
    }

    if (isStale()) {
      autoGeneratedRef.current = true
      generateProjectSummary()
    }
  }, [loading, project])

  const generateProjectSummary = async () => {
    if (!user || !projectId) return

    setGeneratingProjectSummary(true)
    try {
      const tokensRef = collection(db, 'users', user.uid, 'agentTokens')
      const tokensSnap = await getDocs(query(tokensRef))
      const activeToken = tokensSnap.docs.find(d => !d.data().isRevoked)
      if (!activeToken) return

      const token = activeToken.data().token

      const response = await fetch('https://us-central1-town-center-agent.cloudfunctions.net/summarize', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Agent-Token': token
        },
        body: JSON.stringify({ projectId })
      })

      const data = await response.json()

      if (response.ok && data.success && data.summary) {
        const projectRef = doc(db, 'users', user.uid, 'projects', projectId)
        const updateData: any = {
          aiSummary: data.summary,
          summaryGeneratedAt: serverTimestamp()
        }
        if (data.imageUrl) {
          updateData.aiImageUrl = data.imageUrl
        }
        await updateDoc(projectRef, updateData)

        setProject(prev => prev ? {
          ...prev,
          aiSummary: data.summary,
          aiImageUrl: data.imageUrl,
          summaryGeneratedAt: new Date() as any
        } : prev)
      }
    } catch (error) {
      console.error('Error generating project summary:', error)
    } finally {
      setGeneratingProjectSummary(false)
    }
  }

  const getStatusBadge = (status: string) => {
    const styles = {
      active: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
      paused: 'bg-slate-100 text-slate-600 dark:bg-slate-700/50 dark:text-slate-400',
      completed: 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400'
    }
    return styles[status as keyof typeof styles] || styles.active
  }

  const getPriorityColor = (priority: string) => {
    const colors = {
      high: 'border-l-red-500',
      medium: 'border-l-yellow-500',
      low: 'border-l-green-500',
      debug: 'border-l-gray-400'
    }
    return colors[priority as keyof typeof colors] || colors.medium
  }

  if (loading) {
    return (
      <div className="flex justify-center py-12">
        <Spinner size="lg" />
      </div>
    )
  }

  if (!project) {
    return (
      <div className="text-center py-12">
        <h2 className="text-xl font-medium text-gray-900 dark:text-white">
          Project not found
        </h2>
        <Link to="/" className="mt-4 text-blue-600 hover:underline">
          Back to Projects
        </Link>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div className="flex items-center gap-4 min-w-0">
          <Link to="/" className="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 flex-shrink-0">
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </Link>
          <div className="min-w-0">
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white truncate">
              {project.name}
            </h1>
            <p className="text-sm text-gray-500 dark:text-gray-400">
              Last activity: {formatRelativeTime(project.lastActivityAt)}
            </p>
          </div>
        </div>

        {/* GitHub Link */}
        <a
          href={`https://github.com/${project.fullName || project.name}`}
          target="_blank"
          rel="noopener noreferrer"
          className="flex-shrink-0 flex items-center gap-2 px-3 py-1.5 text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white border border-gray-300 dark:border-gray-600 rounded-lg hover:border-gray-400 dark:hover:border-gray-500 transition-colors"
        >
          <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
            <path fillRule="evenodd" clipRule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" />
          </svg>
          GitHub
        </a>
      </div>

      {/* Project Status Card */}
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6">
        <div className="flex items-start justify-between mb-4">
          <h2 className="text-lg font-medium text-gray-900 dark:text-white">
            Project Status
          </h2>
          <div className="flex items-center gap-2">
            <span className="text-xs px-2 py-1 rounded-full bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">
              {workstreams.length} branch{workstreams.length !== 1 ? 'es' : ''}
            </span>
            <button
              onClick={generateProjectSummary}
              disabled={generatingProjectSummary}
              className="p-1.5 text-gray-400 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-gray-100 dark:hover:bg-gray-700 rounded transition-colors disabled:opacity-50"
              title={project.aiSummary ? "Refresh project summary" : "Generate project summary"}
            >
              {generatingProjectSummary ? (
                <svg className="w-4 h-4 animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" />
                </svg>
              ) : (
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
              )}
            </button>
          </div>
        </div>

        {/* AI Summary */}
        <div className="prose prose-sm dark:prose-invert max-w-none">
          {project.aiSummary ? (
            <div className="space-y-4">
              <p className="text-gray-700 dark:text-gray-300">
                {project.aiSummary}
              </p>
              {project.aiImageUrl && (
                <div className="mt-4">
                  <img
                    src={project.aiImageUrl}
                    alt="AI generated representation of project activity"
                    className="rounded-lg shadow-sm border border-gray-100 dark:border-gray-700 w-full max-h-80 object-cover"
                  />
                </div>
              )}
            </div>
          ) : generatingProjectSummary ? (
            <p className="text-gray-500 dark:text-gray-400 italic">
              Generating project summary...
            </p>
          ) : (
            <p className="text-gray-500 dark:text-gray-400 italic">
              {recentUpdates.length > 0
                ? 'AI summary will be generated automatically.'
                : 'No recent activity. Updates will appear here as commits come in.'}
            </p>
          )}
        </div>

        {/* Quick stats */}
        <div className="mt-4 pt-4 border-t border-gray-100 dark:border-gray-700 flex gap-6 text-sm">
          <div>
            <span className="text-gray-500 dark:text-gray-400">Updates today:</span>{' '}
            <span className="font-medium text-gray-900 dark:text-white">
              {recentUpdates.filter(u => {
                const date = u.timestamp?.toDate?.() || new Date(0)
                const today = new Date()
                return date.toDateString() === today.toDateString()
              }).length}
            </span>
          </div>
          <div>
            <span className="text-gray-500 dark:text-gray-400">This week:</span>{' '}
            <span className="font-medium text-gray-900 dark:text-white">
              {recentUpdates.filter(u => {
                const date = u.timestamp?.toDate?.() || new Date(0)
                const weekAgo = new Date()
                weekAgo.setDate(weekAgo.getDate() - 7)
                return date >= weekAgo
              }).length}
            </span>
          </div>
        </div>
      </div>

      {/* Two-column layout */}
      <div className="grid md:grid-cols-2 gap-6">
        {/* Workstreams */}
        <div>
          <h2 className="text-lg font-medium text-gray-900 dark:text-white mb-4">
            Branches
          </h2>

          {workstreams.length === 0 ? (
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6 text-center">
              <p className="text-gray-600 dark:text-gray-400">
                No branches yet.
              </p>
            </div>
          ) : (
            <div className="space-y-2">
              {[...workstreams].sort((a, b) => {
                if (a.status === 'completed' && b.status !== 'completed') return 1
                if (a.status !== 'completed' && b.status === 'completed') return -1
                return 0
              }).map((workstream) => {
                const isCompleted = workstream.status === 'completed'
                return (
                <Link
                  key={workstream.id}
                  to={`/projects/${projectId}/workstreams/${workstream.id}`}
                  className="block bg-white dark:bg-gray-800 rounded-lg shadow hover:shadow-md transition-shadow p-3"
                >
                  <div className="flex items-center justify-between gap-2">
                    <div className="flex items-center gap-2 min-w-0">
                      {isCompleted ? (
                        <svg className="w-4 h-4 text-emerald-500 dark:text-emerald-400 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 11l3-3m0 0l3 3m-3-3v8m8-4a9 9 0 11-18 0 9 9 0 0118 0z" />
                        </svg>
                      ) : (
                        <svg className="w-4 h-4 text-gray-400 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                        </svg>
                      )}
                      <span className={`font-medium text-sm truncate ${isCompleted ? 'text-gray-400 dark:text-gray-500' : 'text-gray-900 dark:text-white'}`}>
                        {workstream.name}
                      </span>
                      {isCompleted ? (
                        <span className="inline-flex items-center gap-1 text-xs px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400 font-medium flex-shrink-0">
                          <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2.5} d="M5 13l4 4L19 7" />
                          </svg>
                          merged
                        </span>
                      ) : (
                        <span className={`text-xs px-2 py-0.5 rounded-full flex-shrink-0 ${getStatusBadge(workstream.status)}`}>
                          {workstream.status}
                        </span>
                      )}
                    </div>
                    <span className={`text-xs flex-shrink-0 whitespace-nowrap ${isCompleted ? 'text-gray-400 dark:text-gray-500' : 'text-gray-500 dark:text-gray-400'}`}>
                      {isCompleted && workstream.mergedAt
                        ? `merged ${formatRelativeTime(workstream.mergedAt)}`
                        : formatRelativeTime(workstream.lastActivityAt)}
                    </span>
                  </div>
                </Link>
                )
              })}
            </div>
          )}
        </div>

        {/* Recent Activity */}
        <div>
          <h2 className="text-lg font-medium text-gray-900 dark:text-white mb-4">
            Recent Activity
          </h2>

          {recentUpdates.length === 0 ? (
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow p-6 text-center">
              <p className="text-gray-600 dark:text-gray-400">
                No activity yet.
              </p>
            </div>
          ) : (
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow overflow-hidden">
              <div className="divide-y divide-gray-100 dark:divide-gray-700">
                {recentUpdates.slice(0, 8).map((update) => (
                  <div
                    key={update.id}
                    className={`px-4 py-3 border-l-4 ${getPriorityColor(update.priority)}`}
                  >
                    <p className="text-sm text-gray-800 dark:text-gray-200 whitespace-nowrap overflow-hidden text-ellipsis">
                      {update.summary.split('\n')[0]}
                    </p>
                    <div className="mt-1 flex items-center gap-2 text-xs text-gray-500 dark:text-gray-400">
                      <span className="font-medium">{update.workstreamName}</span>
                      <span>·</span>
                      <span>{update.tool}</span>
                      <span>·</span>
                      <span>{formatRelativeTime(update.timestamp)}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
